app/routes.py
from flask import Blueprint, render_template, jsonify
from sqlalchemy import create_engine, text
from datetime import datetime, date, time

main = Blueprint('main', __name__)
DATABASE_URI = 'postgresql://postgres:210197@localhost/football_matches_db'
engine = create_engine(DATABASE_URI)

@main.route('/')
def home():
    return render_template('home.html')

@main.route('/footymap')
def footymap():
    return render_template('index.html')


@main.route('/api/stadium-coordinates')
def api_coordinates():
    query = text('SELECT * FROM stadium_coordinates')
    with engine.connect() as conn:
        result = conn.execute(query)
        # Convert result to a list of dictionaries
        data = [dict(zip(result.keys(), row)) for row in result]
    return jsonify(data)

@main.route('/api/matches')
def api_matches():
    query = text('SELECT * FROM football_fixtures')
    with engine.connect() as conn:
        result = conn.execute(query)
        data = []
        for row in result:
            row_dict = {key: (value.isoformat() if isinstance(value, (datetime, date)) else value.strftime('%H:%M:%S') if isinstance(value, time) else value)
                        for key, value in zip(result.keys(), row)}
            data.append(row_dict)
    return jsonify(data)



@main.route('/api/stadium-info')
def api_stadium_info():
    query = text('SELECT * FROM stadium_info')
    with engine.connect() as conn:
        result = conn.execute(query)
        # Convert result to a list of dictionaries
        data = [dict(zip(result.keys(), row)) for row in result]
    return jsonify(data)

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FootyMap - Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <link rel="icon" type="image/x-icon" href="static/images/location.png">

</head>
<body>
    <div class="background-container"> <!-- Use background-container class here -->
        <button class="start-button" onclick="startApp()">Start App</button> <!-- Use start-button class here -->
    </div>

    <script>
        function startApp() {
            window.location.href = "{{ url_for('main.footymap') }}";
        }
    </script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FootyMap</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" type="image/x-icon" href="static/images/location.png">
</head>
<body>
    <div class="container">
        <!-- Sidebar for filtering options -->
        <div class="sidebar">
            <h2>Filter Matches</h2>
            <label for="startDate">Start Date:</label>
            <input type="date" id="startDate" name="startDate" min="2024-09-09">

            <label for="endDate">End Date:</label>
            <input type="date" id="endDate" name="endDate" min="2024-09-09">

            <label for="city">City:</label>
            <input type="text" id="city" placeholder="Enter city name">

            <label for="team">Team:</label>
            <input type="text" id="team" placeholder="Enter team name">

            <button id="filterBtn">Filter Matches</button>
        </div>

        <!-- Map container -->
        <div id="map"></div>
    </div>

    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>